/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       scd4x
 * Model-Version: 2.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "scd4x_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    scd4x_init(SCD41_I2C_ADDR_62);

    uint64_t serial_number = 0;
    sensirion_hal_sleep_us(30000);
    // Ensure sensor is in clean state
    error = scd4x_wake_up();
    if (error != NO_ERROR) {
        printf("error executing wake_up(): %i\n", error);
    }
    error = scd4x_stop_periodic_measurement();
    if (error != NO_ERROR) {
        printf("error executing stop_periodic_measurement(): %i\n", error);
    }
    error = scd4x_reinit();
    if (error != NO_ERROR) {
        printf("error executing reinit(): %i\n", error);
    }
    // Read out information about the sensor
    error = scd4x_get_serial_number(&serial_number);
    if (error != NO_ERROR) {
        printf("error executing get_serial_number(): %i\n", error);
        return error;
    }
    printf("serial number: 0x%" PRIx64 "\n", serial_number);
    //
    // If temperature offset and/or sensor altitude compensation
    // is required, you should call the respective functions here.
    // Check out the header file for the function definitions.
    uint16_t co2_concentration = 0;
    float temperature = 0.0;
    float relative_humidity = 0.0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 5; repetition++) {
        //
        // Wake the sensor up from sleep mode.
        //
        error = scd4x_wake_up();
        if (error != NO_ERROR) {
            printf("error executing wake_up(): %i\n", error);
            continue;
        }
        //
        // Ignore first measurement after wake up.
        //
        error = scd4x_measure_single_shot();
        if (error != NO_ERROR) {
            printf("error executing measure_single_shot(): %i\n", error);
            continue;
        }
        //
        // Perform single shot measurement and read data.
        //
        error = scd4x_measure_and_read_single_shot(
            &co2_concentration, &temperature, &relative_humidity);
        if (error != NO_ERROR) {
            printf("error executing measure_and_read_single_shot(): %i\n",
                   error);
            continue;
        }
        //
        // Print results in physical units.
        //
        printf("CO2 concentration [ppm]: %u\n", co2_concentration);
        printf("Temperature [°C]: %.2f\n", temperature);
        printf("Relative Humidity [RH]: %.2f\n", relative_humidity);
        printf("%s\n", "sleep for 5 minutes until next measurement is due");
        sensirion_hal_sleep_us(300000000);
    }

    return NO_ERROR;
}
